# do not specify a vpc_name it it does not exist from another stack
#vpc_name: "AcrVPC"

app_name: "acr"
key_name: "my-ec2-key-pair"
ami_bastion_name: "MyAcrBastion"
bastion_host_name: "MyAcrBastion"
kds_stream_name: "CarRideStream"
kds_name: "CarRideKDS"
producer_lambda_name: "CarRideProducerLambda"
msk_ec2_type: "kafka.t3.small"
msk_topic_name: "CarRides"

